steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'publish'
  - '--registry=https://us-central1.pkg.dev/$PROJECT_ID/private-marketplace-package'

options:
  logging: CLOUD_LOGGING_ONLY